### 공공시설 데이터와 공원 데이터 합치기

In [20]:
import pandas as pd
data_2018 = pd.read_csv(r'C:\Users\soobin\coding_excuse\공공시설운영현황2018년.csv')
data_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 813 entries, 0 to 812
Data columns (total 23 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       813 non-null    int64
 1   회계연도     813 non-null    int64
 2   지역명      813 non-null    object
 3   자치단체코드   813 non-null    int64
 4   자치단체명    813 non-null    object
 5   시설유형     813 non-null    object
 6   시설구분     813 non-null    object
 7   시설명      813 non-null    object
 8   건립일      813 non-null    object
 9   운영방식     813 non-null    object
 10  건물면적     813 non-null    float64
 11  토지면적     813 non-null    float64
 12  관리인력     813 non-null    int64
 13  연간이용인원   813 non-null    int64
 14  건립비용     813 non-null    int64
 15  취득가액     813 non-null    int64
 16  감가상각액    813 non-null    int64
 17  감가상각누계액  813 non-null    int64
 18  장부가액     813 non-null    int64
 19  내용연수     813 non-null    int64
 20  비용       813 non-null    int64
 21  수익       813 non-null    int64
 22  순수익      813 non-null    int64
dtypes: float64(2), int64(14), object(7)
memory usage: 146.2+ KB

In [21]:
data2018 = data_2018.copy()
data2018 = data2018.iloc[:, [1,4,5,6,7]]
data2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 813 entries, 0 to 812
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   회계연도    813 non-null    int64
 1   자치단체명   813 non-null    object
 2   시설유형    813 non-null    object
 3   시설구분    813 non-null    object
 4   시설명     813 non-null    object
dtypes: int64(1), object(4)
memory usage: 31.9+ KB

In [22]:
data2018['시도'] = data2018['자치단체명'].str[:2]
data2018['시군구'] = data2018['자치단체명'].str[2:]

In [23]:
data2018.drop(columns =  '자치단체명')

     회계연도  시설유형     시설구분           시설명  시도 시군구
0    2018  문화시설   문화예술회관         블루스퀘어  서울  본청
1    2018  문화시설  청소년수련회관      목동청소년수련관  서울  본청
2    2018  체육시설      축구장      서울월드컵경기장  서울  본청
3    2018  문화시설      미술관       서울시립미술관  서울  본청
4    2018  체육시설    육상경기장     잠실올림픽주경기장  서울  본청
..    ...   ...      ...           ...  ..  ..
808  2018  체육시설      축구장  제주종합경기장 주경기장  제주  본청
809  2018  체육시설      수영장     서귀포국민체육센터  제주  본청
810  2018  문화시설      박물관         감귤박물관  제주  본청
811  2018  문화시설      박물관          돌박물관  제주  본청
812  2018  문화시설   문화예술회관      서귀포예술의전당  제주  본청

[813 rows x 6 columns]

In [24]:
data2018.rename(columns={'회계연도': '년도'}, inplace=True)
data2018.drop(columns =  '시설유형')
data2018.drop(columns = '시설구분')
order = ['년도', '시도', '시군구', '시설명']
data2018 = data2018[order]
data2018

       년도  시도 시군구           시설명
0    2018  서울  본청         블루스퀘어
1    2018  서울  본청      목동청소년수련관
2    2018  서울  본청      서울월드컵경기장
3    2018  서울  본청       서울시립미술관
4    2018  서울  본청     잠실올림픽주경기장
..    ...  ..  ..           ...
808  2018  제주  본청  제주종합경기장 주경기장
809  2018  제주  본청     서귀포국민체육센터
810  2018  제주  본청         감귤박물관
811  2018  제주  본청          돌박물관
812  2018  제주  본청      서귀포예술의전당

[813 rows x 4 columns]

In [26]:
# 2019년 데이터
# 데이터 불러오기
data_2019 = pd.read_csv(r'C:\Users\soobin\coding_excuse\공공시설운영현황2019년.csv')

# 필요한 데이터만 추출 (회계연도, 자치단체명, 시설유형, 시설구분, 시설명)
data2019 = data_2019.copy()
data2019 = data2019.iloc[:, [1,4,5,6,7]]

# 서울본청에서 서울과 본청으로 나누기
data2019['시도'] = data2019['자치단체명'].str[:2]
data2019['시군구'] = data2019['자치단체명'].str[2:]

# 컬럼 이름 변경 / 필요한 데이터만 다시 추출하기
data2019.rename(columns={'회계연도': '년도'}, inplace=True)
data2019.drop(columns =  '자치단체명')
data2019.drop(columns =  '시설유형')
data2019.drop(columns = '시설구분')

# 재배열
order = ['년도', '시도', '시군구', '시설명']
data2019 = data2019[order]
data2019

       년도  시도 시군구         시설명
0    2019  서울  본청   잠실올림픽주경기장
1    2019  서울  본청       서울도서관
2    2019  서울  본청       잠실야구장
3    2019  서울  본청   서울에너지드림센터
4    2019  서울  본청     한성백제박물관
..    ...  ..  ..         ...
865  2019  제주  본청    4.3평화기념관
866  2019  제주  본청      제주아트센터
867  2019  제주  본청  제주세계자연유산센터
868  2019  제주  본청    제주월드컵경기장
869  2019  제주  본청      제주돌박물관

[870 rows x 4 columns]

In [27]:
# 2020년 데이터
# 데이터 불러오기
data_2020 = pd.read_csv(r'C:\Users\soobin\coding_excuse\공공시설운영현황2020년.csv')

# 필요한 데이터만 추출 (회계연도, 자치단체명, 시설유형, 시설구분, 시설명)
data2020 = data_2020.copy()
data2020 = data2020.iloc[:, [1,4,5,6,7]]

# 서울본청에서 서울과 본청으로 나누기
data2020['시도'] = data2020['자치단체명'].str[:2]
data2020['시군구'] = data2020['자치단체명'].str[2:]

# 컬럼 이름 변경 / 필요한 데이터만 다시 추출하기
data2020.rename(columns={'회계연도': '년도'}, inplace=True)
data2020.drop(columns =  '자치단체명')
data2020.drop(columns =  '시설유형')
data2020.drop(columns = '시설구분')

# 재배열
order = ['년도', '시도', '시군구', '시설명']
data2020 = data2020[order]
data2020

       년도  시도 시군구        시설명
0    2020  서울  본청   창동청소년수련관
1    2020  서울  본청  서대문청소년수련관
2    2020  서울  본청   보라매안전체험관
3    2020  서울  본청   광나루안전체험관
4    2020  서울  본청  서울도시건축전시관
..    ...  ..  ..        ...
888  2020  제주  본청  서귀포국민체육센터
889  2020  제주  본청      감귤박물관
890  2020  제주  본청   제주별빛누리공원
891  2020  제주  본청    제주안전체험관
892  2020  제주  본청   서귀포예술의전당

[893 rows x 4 columns]

In [28]:
# 2020년 데이터
# 데이터 불러오기
data_2022 = pd.read_csv(r'C:\Users\soobin\coding_excuse\공공시설운영현황2022년.csv')

# 필요한 데이터만 추출 (회계연도, 자치단체명, 시설유형, 시설구분, 시설명)
data2022 = data_2022.copy()
data2022 = data2022.iloc[:, [1,4,5,6,7]]

# 서울본청에서 서울과 본청으로 나누기
data2022['시도'] = data2022['자치단체명'].str[:2]
data2022['시군구'] = data2022['자치단체명'].str[2:]

# 컬럼 이름 변경 / 필요한 데이터만 다시 추출하기
data2022.rename(columns={'회계연도': '년도'}, inplace=True)
data2022.drop(columns =  '자치단체명')
data2022.drop(columns =  '시설유형')
data2022.drop(columns = '시설구분')

# 재배열
order = ['년도', '시도', '시군구', '시설명']
data2022 = data2022[order]
data2022

       년도  시도  시군구        시설명
0    2022  서울   본청      서울도서관
1    2022  서울   본청      서울식물원
2    2022  서울   본청    서울공예박물관
3    2022  서울   본청   보라매안전체험관
4    2022  서울   본청  서울도시건축전시관
..    ...  ..  ...        ...
393  2022  경남  고성군  고성군국민체육센터
394  2022  경남  남해군    남해실내체육관
395  2022  경남  남해군  남해군국민체육센터
396  2022  경남  하동군  해양플랜트연구단지
397  2022  경남  함양군  함양군문화예술회관

[398 rows x 4 columns]

In [35]:
data = pd.concat([data2018, data2019, data2020, data2022], ignore_index=True)
data.to_csv(r'C:\Users\soobin\coding_excuse\공공시설.csv',index=False, encoding='utf-8-sig')
data

        년도  시도  시군구        시설명
0     2018  서울   본청      블루스퀘어
1     2018  서울   본청   목동청소년수련관
2     2018  서울   본청   서울월드컵경기장
3     2018  서울   본청    서울시립미술관
4     2018  서울   본청  잠실올림픽주경기장
...    ...  ..  ...        ...
2969  2022  경남  고성군  고성군국민체육센터
2970  2022  경남  남해군    남해실내체육관
2971  2022  경남  남해군  남해군국민체육센터
2972  2022  경남  하동군  해양플랜트연구단지
2973  2022  경남  함양군  함양군문화예술회관

[2974 rows x 4 columns]